//@prepros-append ../../vendors/jquery/dist/jquery.js
//@prepros-append ../../vendors/jquery-waypoints/waypoints.js
//@prepros-append ../../vendors/jquery.validation/dist/jquery.validate.js
//@prepros-append ../../vendors/classie.js
//@prepros-append responsive-nav.js
//@prepros-append fastclick.js
//@prepros-append scroll.js
//@prepros-append fixed-responsive-nav.js
//@prepros-append contact.js